### ISSUE TITLE
selected prop not working

### ISSUE THREAD

**Issue by MathiasLund** [exponentjs/react-native-tab-navigator#95] opened 2016-08-21 15:22 UTC
Hi, great repo!

I have this problem that I can't get the 'selected' prop working.
It works perfectly without the prop, but when I for instance do:

`selected={this.props.selectedTab === 'home'}`

it says 
"Warning: There is an internal error in the React performance measurement code. Did not expect componentDidMount timer to start while render timer is still in progress for another instance."

and the tab bar is gone.

Any help appreciated!

**Comment by ide** [comment] 2016-08-22 20:03
Is this happening in a very simple project? I want to know if the issue is with your app code or this component.

**Comment by MathiasLund** [comment] 2016-08-25 17:42
Yeah ok, it's a problem with my project - thanks anyway :)

**Comment by ide** [comment] 2016-08-25 17:55
Thanks for checking. I will close this issue then.

**Closed as completed by ide** 2016-08-25 17:55 UTC
